AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/*'
    - 'Gemfile'
    - 'Rakefile'
  TargetRubyVersion: 2.6

Style/Documentation:
  Exclude:
    - 'app/helpers/**/*'
    - 'app/controllers/**/*'
    - 'app/mailers/**/*'
    - 'app/models/application_record.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 100
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Style/AutoResourceCleanup:
  Description: 'Suggests the usage of an auto resource cleanup version of a method (if available).'
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/CollectionMethods:
  Description: 'Preferred collection methods.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size'
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3
